services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    volumes:
      - ./src:/src

    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=123456

    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --reload"

    depends_on:
      - database

  database:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=123456

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

