"""Initial

Revision ID: 21552a909830
Revises: 
Create Date: 2024-04-28 09:24:37.563519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21552a909830'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategories_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_title', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount_price', sa.Float(), nullable=False),
    sa.Column('product_balance', sa.Integer(), nullable=False),
    sa.Column('product_characteristics', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_table')
    op.drop_table('subcategories_table')
    op.drop_table('categories_table')
    # ### end Alembic commands ###
